spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://47.93.37.94:33306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null  # 结果集返回为空或null 的集合时直接不显示
#日志配置（已注释）
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: D:/var/log/tomcat/sell.log
#  level: debug   #设置日志级别
server:
  servlet:
    context-path: /sell
